services:
  redis:
    image: redis:alpine
    healthcheck:
      # This ensures that Redis not only responds but also returns a PONG response
      test: ["CMD", "sh", "-c", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 1s
      retries: 3
    restart: unless-stopped
  server:
    image: ghcr.io/kweeuhree/distributed-rate-limiter:latest
    container_name: app
    depends_on:
      redis:
        condition: service_healthy
    build:
      context: .
    volumes:
      #  Mount secret files in read-only mode
      - ./redisSecrets.txt:/run/secrets/redisSecrets:ro
    environment:
      PORT: 4000
    ports:
      - "4000:4000"

    restart: unless-stopped
